### ISSUE TITLE
AzureDNS Provider Issue - 'ServicePrincipalCredentials' object has no attribute 'get_token'

### ISSUE THREAD

**Issue by chrisg666** [octodns/octodns-azure#17] opened 2022-01-30 15:24 UTC
Hi,

I have an old working octodns 9.10 install on a python27 env - that manages a zone on a split-auth dns across aws and azure

I have now built a new platform to replace the above with octodns 9.14 on a python39 env and ported the config files across from the old env. 

Have updated the setup for the new octodns_azure.AzureProvider provider (old setup is using octodns.provider.azuredns.AzureProvider)

Octodns read type actions on the new setup appear to work ok (eg on say an octodns-sync dry run etc)

But write actions (eg on an octodns-sync --doit to update a zone) ends up with a failure on the azure target (works fine on the route53 target) - the Azure failure is flagged with the following: -
```
   AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
```
I know the Azure libraries for Python have undergone rework in the past couple of years
Where ServicePrincipalCredentials in the azure.common lib was used for authentication previously but that's been replaced with the azure-identity library (?)

Has anyone got any pointers on what the problem is here / where it may lay ?

My ~config.yaml file is: -

```---
manager:
  max_workers: 2

providers:
  config:
    class: octodns.provider.yaml.YamlProvider
    directory: .\test-zone
    default_ttl: 3600
    enforce_order: True
  azuredns:
    class: octodns_azure.AzureProvider
    client_id:  env/AZURE_CLIENT_ID
    key: env/AZURE_KEY
    directory_id: env/AZURE_DIRECTORY_ID
    sub_id: env/AZURE_SUB_ID
    resource_group: env/AZURE_RESOURCE_GROUP
  route53:
    class: octodns_route53.Route53Provider
    access_key_id: env/AWS_ACCESS_KEY_ID
    secret_access_key: env/AWS_SECRET_ACCESS_KEY

zones:
  abcdefg.net.:
    sources:
      - config
    targets:
      - azuredns
      - route53
```

What is seen when doing a octodns-sync --doit that will involve a zone change, is as follows: -

```~>octodns-sync --config=abcdefg-test-config.yaml --doit

2022-01-29T12:26:58  [9364] INFO  Manager __init__: config_file=abcdefg-test-config.yaml
2022-01-29T12:26:58  [9364] INFO  Manager __init__:   max_workers=2
2022-01-29T12:26:58  [9364] INFO  Manager __init__:   include_meta=False
2022-01-29T12:26:59  [9364] INFO  Manager sync: eligible_zones=[], eligible_targets=[], dry_run=False, force=False, plan_output_fh=<stdout>
2022-01-29T12:26:59  [9364] INFO  Manager sync:   zone=abcdefg.net.
2022-01-29T12:26:59  [9364] INFO  Manager sync:   sources=['config'] -> targets=['azuredns', 'route53']
2022-01-29T12:26:59  [5208] INFO  YamlProvider[config] populate:   found 125 records, exists=False

2022-01-29T12:26:59  [5208] INFO  AzureProvider[azuredns] plan: desired=abcdefg.net.
2022-01-29T12:26:59  [5208] INFO  azure.identity._internal.get_token_mixin ClientSecretCredential.get_token succeeded
2022-01-29T12:27:01  [5208] INFO  AzureProvider[azuredns] populate: found 126 records, exists=True
2022-01-29T12:27:01  [5208] INFO  AzureProvider[azuredns] plan:   Creates=0, Updates=1, Deletes=0, Existing Records=126

2022-01-29T12:27:01  [5208] INFO  Route53Provider[route53] plan: desired=abcdefg.net.
2022-01-29T12:27:03  [5208] INFO  Route53Provider[route53] populate:   found 126 records, exists=True
2022-01-29T12:27:03  [5208] INFO  Route53Provider[route53] plan:   Creates=0, Updates=1, Deletes=0, Existing Records=126

2022-01-29T12:27:03  [9364] INFO  Manager
********************************************************************************
* abcdefg.net.
********************************************************************************
* azuredns (AzureProvider)
*   Update
*     <ARecord A 300, tell.abcdefg.net., ['1.1.1.1']> ->
*     <ARecord A 300, tell.abcdefg.net., ['3.3.3.3']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=126

* route53 (Route53Provider)
*   Update
*     <ARecord A 300, tell.abcdefg.net., ['1.1.1.1']> ->
*     <ARecord A 300, tell.abcdefg.net., ['3.3.3.3']> (config)
*   Summary: Creates=0, Updates=1, Deletes=0, Existing Records=126
********************************************************************************


2022-01-29T12:27:03  [9364] INFO  AzureProvider[azuredns] apply: making 1 changes to abcdefg.net.
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python39\Scripts\octodns-sync.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python39\lib\site-packages\octodns\cmds\sync.py", line 38, in main
    manager.sync(eligible_zones=args.zone, eligible_sources=args.source,
  File "C:\Program Files\Python39\lib\site-packages\octodns\manager.py", line 468, in sync
    total_changes += target.apply(plan)
  File "C:\Program Files\Python39\lib\site-packages\octodns\provider\base.py", line 181, in apply
    self._apply(plan)
  File "C:\Program Files\Python39\lib\site-packages\octodns_azure\__init__.py", line 1513, in _apply
    getattr(self, f'_apply_{class_name}')(change)
  File "C:\Program Files\Python39\lib\site-packages\octodns_azure\__init__.py", line 1437, in _apply_Update
    profile = self._get_tm_for_dynamic_record(new)
  File "C:\Program Files\Python39\lib\site-packages\octodns_azure\__init__.py", line 636, in _get_tm_for_dynamic_record
    return self._get_tm_profile_by_name(name)
  File "C:\Program Files\Python39\lib\site-packages\octodns_azure\__init__.py", line 632, in _get_tm_profile_by_name
    return self._get_tm_profile_by_id(profile_id)
  File "C:\Program Files\Python39\lib\site-packages\octodns_azure\__init__.py", line 621, in _get_tm_profile_by_id
    self._populate_traffic_managers()
  File "C:\Program Files\Python39\lib\site-packages\octodns_azure\__init__.py", line 605, in _populate_traffic_managers
    for profile in list_profiles(self._resource_group):
  File "C:\Program Files\Python39\lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "C:\Program Files\Python39\lib\site-packages\azure\mgmt\trafficmanager\operations\_profiles_operations.py", line 413, in get_next
    pipeline_response = self._client._pipeline.run(request, stream=False, **kwargs)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 211, in run
    return first_node.send(pipeline_request)  # type: ignore
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\_base.py", line 71, in send
    response = self.next.send(request)
  [Previous line repeated 2 more times]
  File "C:\Program Files\Python39\lib\site-packages\azure\mgmt\core\policies\_base.py", line 47, in send
    response = self.next.send(request)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\policies\_redirect.py", line 158, in send
    response = self.next.send(request)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\policies\_retry.py", line 445, in send
    response = self.next.send(request)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 117, in send
    self.on_request(request)
  File "C:\Program Files\Python39\lib\site-packages\azure\core\pipeline\policies\_authentication.py", line 94, in on_request
    self._token = self._credential.get_token(*self._scopes)
AttributeError: 'ServicePrincipalCredentials' object has no attribute 'get_token'
```

thanks in advance,
Chris

**Comment by viranch** [comment] 2022-02-01 06:45
I can reproduce this. This is likely because `azure-identity` was bumped when the provider was extracted to separate repo in https://github.com/octodns/octodns/pull/833 (2nd commit in this repo had a newer version https://github.com/octodns/octodns-azure/blob/f4274f1a4c3ccb910ad5b101a35fe0f2b5841fa1/requirements.txt#L7).

I'll work on a fix for this.

**Closed** 2022-02-01 16:55 UTC
